### PR TITLE
Layout compatibility using event.key

### PR DESCRIPTION
**Pull request by Razboi**
Using event.keyCode limits the keyboard layout compatibility. Added a trigger.key property for triggering with event.key

### CODE REVIEW

**Comment by Razboi** [comment]
Ops. Messed up building for my own project. It's reverted now

**Review by Teippo2020 — COMMENTED** [review]
Awesome feature!

**Review by Teippo2020 — APPROVED** [review]
Awesome feature!

**Comment by Teippo2020** [comment]
To the maintainer, are there any plans to merge this feature? The library basically doesn't work on MAC for the character @

**Comment by abinavseelan** [comment]
Apologises for not getting back to this earlier. 😞 Thank you so much for raising this fix @Razboi 🙂 

Since this is a breaking change, can we assimilate this change into https://github.com/abinavseelan/react-input-trigger/tree/pre-release/2.0.0. This branch has some more breaking changes that fix non-standard input elements as highlighted in #10 and would be the next major version release for this package.

**Comment by Teippo2020** [comment]
That would be awesome! In the meantime (because I needed this feature so much) I created a fork and published it to npm,  just in case anyone needs this feature before the release.

https://www.npmjs.com/package/react-input-trigger-fork

**Pull request closed without merging**
